### PR TITLE
GPS messages

### PR DESCRIPTION
**Pull request by davidfokkema**
Process GPS messages, and program the GPS receiver.

### CODE REVIEW

**Comment by davidfokkema** [comment]
Darn! After hours wasted, I'm pretty sure we're losing bytes. Nothing we can do, I'm afraid. I think we're being bitten by this bug report on pylibftdi: http://www.bytebucket.org/codedstructure/pylibftdi/issue/11/ft232h-serial-mode-unreliable.

It is long standing, and I don't know if there will be any progress on the short term. Do we have to switch libraries again? I checked, it is all abstracted away into ftdi_chip.py. Apart from burning the firmware in HiSPARC III hardware, alas.

**Comment by 153957** [comment]
Probably caused by `pylibftdi`. Because, as far as I know, both DSPMon and HiSPARC DAQ can talk/listen to the GPS properly.

**Comment by davidfokkema** [comment]
The bug report is on pylibftdi. But it might be libftdi. Or...?

**Comment by tomkooij** [comment]
Interesting problem for a rainy evening...

An old UART/FTDI device is dropping bytes but a newer is not. Are you reading data fast/often enough? the ft232r has a small buffer. Are you sure it is not overflowing?

You are reading 62 bytes at a time (READ_SIZE in pysparc/ftdi_chip.py)? I haven't looked into the ft232r datasheet thoroughly but it seems you can read up to 4096 bytes at a time. USB frames are 64 bytes. Furthermore, libftdi supports much bigger readbuffers.

I'd try READ_SIZE 4096

**Comment by davidfokkema** [comment]
Warning: do not spend much time on this! It is not a bug on our side. It is somewhere in the supporting libraries. Somewhere. They have reported this as a bug. Unless you're willing to debug a hardware device and dive into c-code in multiple libraries...

**Comment by davidfokkema** [comment]
Bytes go missing every twenty bytes or so. So the read size is not the problem. Unfortunately.

**Comment by tomkooij** [comment]
Too bad... I won't spend time on this :) I was just fascinated by (and learning from) this wrapping/abstracting code using classes.

Nasty bug! I would write the test script in C using libftdi and see if the problem is reproducible to rule out libftdi.

**Comment by davidfokkema** [comment]
Wrapping is nice. You don't want to see the original code. This bug is very nasty. It's not fun trying to get code to work if your code is not the problem. Writing a test program in C is a good idea. First, let's check other trivial things. 

@153957: could you swap the gps and master cable on the device side? Maybe it's the cable.

**Comment by tomkooij** [comment]
Argh. I lied. I'm drinking coffee and reading libftdi code. (Fortunately my ftdi dongle is FT232RL, or I'd be wasting half a day tinkering...) This is like an addiction.

I stumpled upon your bug report about ftdi latency timer being off: http://www.bytebucket.org/codedstructure/pylibftdi/issue/16/linux-read-timeout-not-respected-high-cpu
From your bugreport, I conclude (guess) pylibftdi is **not setting the latency timer**. Latency should be 16ms, but it seems about 1 ms. Another guess is that FT232R is broken and latency is not 16ms default as per datasheet. The "official closed source" driver probably knows.

Google connects 1ms latency to FT232H (=R?) dropping bytes (in an libftdi example)! https://github.com/legege/libftdi/blob/master/examples/stream_test.c (line 195)

My guess is that pylibftdi should set latency to 16ms, but it does not. (by calling ftdi_set_latency_timer() from libftdi) http://www.intra2net.com/en/developer/libftdi/documentation/group__libftdi.html#ga3e0227b0c7aa859d2d2afb5ffa4c8466)

If I had a FT232R board lying around, I'd actually write a patch and test.

**Comment by 153957** [comment]
@davidfokkema Done.

**Comment by davidfokkema** [comment]
Thanks, @153957. So, the cable is not the issue.

**Comment by tomkooij** [comment]
@davidfokkema have you fixed and/or ruled out: http://www.bytebucket.org/codedstructure/pylibftdi/issue/16/linux-read-timeout-not-respected-high-cpu ? (see earlier comment)

**Comment by davidfokkema** [comment]
@tomkooij I was working on it (mostly in my head). I don't have much time right now, :-/. Anyway: I don't see how latency could be a problem here. I'm reading as fast as I can, and I should be receiving all bytes as long as the buffer does not fill up. I'm seeing problems in the first tens of bytes of the first message after turning on the GPS. Google connects incorrectly. The test code is for an FT2232H, which is an entirely different beast.

My bug report regarding the read timeout and corresponding high cpu usage only manifests itself on linux on some (older?) laptops. On my Mac or modern linux, that is not a problem. Next time I'm at Nikhef, I'll hook up my Mac and see if the results are any better.

I hate these kinds of problems. Figuring out byte streams and crafting messages, ok. Reading documentation and figuring out the correct order of low-level commands and protocols to flash an EEPROM, ok. Dealing with strange bugs probably deep down the USB stack, not fun.

**Comment by tomkooij** [comment]
I doo think latency matters. (Or could matter). For the ftdi latency means: send the buffer when the laterncy timer expires even if the buffer is not full. For 1ms latency this probably means sending the buffer many times per byte, ie sending lots of empty buffers.

Can a userland driver (libftdi and/or libusb) keep up with all these packets? I'm not sure how the kernel handles these.

I'd just set the latency to 16ms anyway. Regardless if it fixes the bug or not.

**Comment by davidfokkema** [comment]
It's hard to know what happens on what level. If I have time, I'll try. But it works for HiSPARC II and III without problems.

**Comment by davidfokkema** [comment]
@tomkooij you are amazing. The call to set_latency_timer() fixed the read timeout problem on linux. Do you want to add a comment to the original bug report?

Alas, this doesn't fix the GPS bug. I'm signing off for now. See you at Nikhef.

**Comment by tomkooij** [comment]
@davidfokkema I can't login to bytebucket.org at all (can't create account, no login using google, facebook etc). So I can't post there. Perhaps it's just a temporarily thing. I'll try again tomorrow. 

Too bad it doesn't fix the GPS bug. I was wondering if libftdi forgets to sets CTS/DTS flowcontrol (or some other flow control) between the FTDI and Trimble board and the UART buffer is overrun. But since your losing data in the first few bytes, that seems unreasonable. Even without flow control the buffer should not be full... 
This possibility should be eliminated by either flushing the buffers before first read() or actually setting the handshakes. But I cannot image you would lose something in the first bytes. Then again, perhaps you lose byte 128.

Trimble uses 9600, *8O1* (odd-parity?!?!?) I wonder if the FT232R autodetects that setting correctly. Could that be the reason for dropping bytes? Can you even read some bytes correctly with a wrong parity mode (9N1?!?!?). Anyway, try reading the parity mode.

**Comment by 153957** [comment]
Try via https://bitbucket.org instead of https://bytebucket.org , should be the same thing though...

**Comment by davidfokkema** [comment]
@tomkooij if you're feeling adventurous, send me an ssh public key and I'll set you up for remote access.

**Comment by davidfokkema** [comment]
Thanks, Tom, this saved my day!

**Comment by davidfokkema** [comment]
The GPS messages code is now quite a bit cleaner than the 'regular' messages code. I like it. And it works. Next step: configuration of the GPS. Getting there... getting there... slowly.

**Pull request merged**
