### PR TITLE
Patch linesettings

### PR DESCRIPTION
**Pull request by tomkooij**
This is a patch to allow linesettings to be set in FtdiChip()

This sets default linesettings to 9600,8,N,1 using libftdi::ftdi_set_line_settings() , pylibftdi::Device() does not automatically set linesettings but relies on hardware? default linesettings. Dangerous!

Trimble TSIP is supposed to be 9600,8,O,1 (odd parity). This is now set in TrimbleGPS() in hardware.py

Todo:
- [ ] Add unittest for default linesettings
- [x] remove baudrate from linesettings. Baudrate is controlled by Device.baudrate property. ftdi_set_baudrate should *not* be called by Ftdi_chip().
- [x] handle databits (7, 8). ~~For some reason ftdi_set_line_settings does not set databits.~~  Embarassing bug fixed in a2d760f
- [x] Test trimble TSIP at 9600,8,O,1 using TrimbleGPS()

### CODE REVIEW

**Comment by davidfokkema** [comment]
I think the line settings are discovered, or pylibftdi intends to set them correctly. We can explicitly set them, but maybe first check the settings if you just open the device?

**Comment by davidfokkema** [comment]
If this fixes the gps problem, I'll be overjoyed.

**Comment by tomkooij** [comment]
On my laptop linesettings are *not* changed and/or set by pylibftdi.

If I set 8O1 it stays 8O1 until I manually change it back. Probably reverts to 8N1 after powercycle but I have not tested that.

I need to explicitely set 8O1 to be able to read from an arduino sending at (9600, 8O1). Otherwise I recieve about half the data and garbage. Parity is not autodiscovered.

**Comment by davidfokkema** [comment]
Ok, that's encouraging!

**Comment by 153957** [comment]
@tomkooij hint: Since you branched of the gps-messages branch you can also create a pull request from this to that brach, instead of master. That keeps the Changes and Commits in this Pull Request a bit cleaner, showing only the differences between your branch and the gps-messages branch. However! GitHub annoyingly does not allow you to change the target of an existing Pull Request. Which can be extra annoying if you were to do as i just suggested and we merged the gps-messages branch into master before your branch is merged into gps-messages... Anyhow, we can always just merge branches locally (independent of PR)... It would just be nice if GitHub allowed you to change the target after PR creation... nevermind. :)

**Comment by tomkooij** [comment]
Setting parity to odd fixed the GPS messages bug!

**Comment by 153957** [comment]
Awesome 🙏🎊

**Comment by davidfokkema** [comment]
Wow. Just wow.

**Comment by davidfokkema** [comment]
Merged into gps-messages. Thanks, Tom!

**Pull request closed without merging**
